### ISSUE TITLE
Empty lock screen

### ISSUE THREAD

**Issue by Stardust-kyun** [KpwnZ/Bug-report-feature-request-for-SimpleLS-2#22]
iPhone 7, iOS 13.3, lock screen is completely blank until you unlock the phone.

**Comment by tdadvocate** [comment]
This is due to a change with how the iOS 13.3 lockscreen is handled by iOS. I have linked a solution for the problem from a well known developer. Not sure if this is exactly the case for this bug but it might be worth looking into at the very least. 

https://twitter.com/aydenpanhuyzen/status/1205981139086782469?s=21

**Comment by KpwnZ** [comment]
Hi, beta version has fixed the bug. I will close this issue.
